package kr.ac.kopo.jeonse.domain.jeonse.domain;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class BuildingRegister {
    private String REGISTER_PK;
    private String REGISTER_CATEGORY_CODE;
    private String REGISTER_CATEGORY_NAME;
    private String REGISTER_TYPE_CODE;
    private String REGISTER_TYPE_NAME;
    private String LAND_LOCATION;
    private String ROAD_LAND_LOCATION;
    private String BUILDING_NAME;
    private String SIGUNGU_CODE;
    private String BJDONG_CODE;
    private String LAND_CATEGORY_CODE;
    private String BUN;
    private String JI;
    private String SPECIAL_LAND_NAME;
    private String BLOCK;
    private String LOT;
    private String OUTER_AREA;
    private String NEW_ADDRESS_ROAD_CODE;
    private String NEW_ADDRESS_LEGAL_CODE;
    private String NEW_ADDRESS_ABOVE_BELOW_CODE;
    private String NEW_ADDRESS_MAIN_NUMBER;
    private String NEW_ADDRESS_SUB_NUMBER;
    private String DONG_NAME;
    private String MAIN_ATTACH_CATEGORY_CODE;
    private String MAIN_ATTACH_CATEGORY_NAME;
    private String LAND_AREA_SQM;
    private String BUILDING_AREA_SQM;
    private String BUILDING_COVERAGE_RATIO;
    private String TOTAL_FLOOR_AREA_SQM;
    private String FLOOR_AREA_RATIO_CALCULATION_AREA_SQM;
    private String FLOOR_AREA_RATIO;
    private String STRUCTURE_CODE;
    private String STRUCTURE_CODE_NAME;
    private String OTHER_STRUCTURE;
    private String MAIN_USE_CODE;
    private String MAIN_USE_CODE_NAME;
    private String OTHER_USE;
    private String ROOF_CODE;
    private String ROOF_CODE_NAME;
    private String OTHER_ROOF;
    private String HOUSEHOLD_COUNT;
    private String HOUSEHOLD_UNIT_COUNT;
    private String HEIGHT_M;
    private String ABOVE_GROUND_FLOOR_COUNT;
    private String UNDERGROUND_FLOOR_COUNT;
    private String PASSENGER_ELEVATOR_COUNT;
    private String EMERGENCY_ELEVATOR_COUNT;
    private String SUBSIDIARY_BUILDING_COUNT;
    private String SUBSIDIARY_BUILDING_AREA_SQM;
    private String TOTAL_BUILDING_FLOOR_AREA_SQM;
    private String INDOOR_MECHANICAL_PARKING_COUNT;
    private String INDOOR_MECHANICAL_PARKING_AREA_SQM;
    private String OUTDOOR_MECHANICAL_PARKING_COUNT;
    private String OUTDOOR_MECHANICAL_PARKING_AREA_SQM;
    private String INDOOR_SELF_PARKING_COUNT;
    private String INDOOR_SELF_PARKING_AREA_SQM;
    private String OUTDOOR_SELF_PARKING_COUNT;
    private String OUTDOOR_SELF_PARKING_AREA_SQM;
    private String PERMIT_DATE;
    private String CONSTRUCTION_START_DATE;
    private String USAGE_APPROVAL_DATE;
    private String PERMIT_NUMBER_YEAR;
    private String PERMIT_NUMBER_AGENCY_CODE;
    private String PERMIT_NUMBER_AGENCY_NAME;
    private String PERMIT_NUMBER_CATEGORY_CODE;
    private String PERMIT_NUMBER_CATEGORY_NAME;
    private String UNIT_NUMBER;
    private String ENERGY_EFFICIENCY_GRADE;
    private String ENERGY_SAVING_RATIO;
    private String ENERGY_EPI_SCORE;
    private String ECO_FRIENDLY_BUILDING_GRADE;
    private String ECO_FRIENDLY_BUILDING_SCORE;
    private String INTELLIGENT_BUILDING_GRADE;
    private String INTELLIGENT_BUILDING_SCORE;
    private String CREATION_DATE;
    private String SEISMIC_DESIGN_APPLICATION;
    private String SEISMIC_ABILITY;
}
