name: YEBANG CI/CD
run-name: ${{ github.actor }} - ${{ github.event_name }}
on:
  push:
    branches:
      - main
      -
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run shell script on remote server to stop service and move file to archive
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "test" > test.txt

      # Set up JDK 17
      - uses: actions/checkout@v3
      - name: Setup Java 17
        uses: actions/setup-java@v1
        with:
          java-version: 17


      # Build with Maven
      - name: Maven package
        run: |
          mvn package -DskipTests

      # Deploy to remote server
      - name: Deploy to remote server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SSH_USERNAME }}
          server: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: target/*.jar
          remote_path: /home/vincentkim0503
          sftp_only: true


